### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by philliplurge** [flowryaan/mailman#1]
....

**Comment by philliplurge** [comment]
Incomplete response received from application

ich komme nicht weiter wass muss ich jetzt machen..

**Comment by philliplurge** [comment]
es läuft halbwegs

http://pastebin.com/pTrUDCvR

hatte die datenbank sock nicht geändert ^^
kann mich aber trozdem nicht einloggen :/

bitte um schnelle hilfe

**Comment by flowryaan** [comment]
Ich habe vergessen zu erwähnen, dass ich zurzeit für die Passwort Generierung den SSHA512 statt dem SHA512-CRYPT verwende. 

Dazu müsste man in der `/etc/dovecot/dovecot-sql.conf` den Wert von `default_pass_scheme` auf SSHA512 ändern und natürlich dann das Passwort des Mail Admin Users manuell mit `doveadm pw -s SSHA512` erzeugen und in der DB setzen.

Der SSHA512 ist nur eine vorübergehende Lösung, da ja im Tutorial vom Mailserver der SHA512-CRYPT verwendet wird, sollte auch Mailman diesen unterstützen, jedoch gab es ein paar Probleme mit dem SHA512-CRYPT beim entwickeln.

Ich werde versuchen in den nächsten Tagen das zu ändern und auch eine Anleitung verfassen :)

**Comment by philliplurge** [comment]
Okay, Funktioniert,

Aber wie bekomme ich es hin dass dass design auch angezeigt wird ?? habe lediglich eine ziemliches Seiten salat >_<

von dem design keine spur..

auf welchen ordner muss ich nginx genau verweisen lassen bzw wass muss ich ändern?

**Comment by flowryaan** [comment]
Das freut mich :) 

In nginx folgenden Ordner als Document Root setzen:

```
/home/deploy/mailman/current/public;
```

Es kann sein das du noch die Assest kompilieren musst. 
Einfach als `deploy` Benutzer  im Ordner `/home/deploy/mailman/current` folgenden Befehl ausführen:

```
RAILS_ENV=production bundle exec rake assets:precompile
```

**Comment by philliplurge** [comment]
den ordner `/home/deploy/mailman/current` kann mein system nicht finden bzw ich auch nicht :/

**Comment by flowryaan** [comment]
Den `current` Ordner gibt es nur wenn du es mit Capistrano (wie im GoRails Tutorial) deployst. Es ist ein Symlink auf die aktuellste Version die von GitHub geklont wird. Ansonsten musst du nginx als Document Root nur den `public` Ordner von Rails geben. Der `public` befindet sich im Git Repository von mailman.

**Comment by flowryaan** [comment]
Ich habe jetzt einen Guide hinzugefügt und hoffe er hilft dir! Falls du das Passwort von SHA512-CRYPT auf SSHA512 geändert hast müsstest du das wieder rückgängig machen da ich es nun gefixt hab. 

Auch der Fehler von deinem Log File sollte behoben sein:

```
ArgumentError (invalid base64):
```

Wenn du ein Problem hast einfach eine neues Issue öffnen :)
