### ISSUE TITLE
Rails-Anwendung

### ISSUE THREAD

**Issue by philliplurge** [flowryaan/mailman#3]
Guten Morgen ^^,

Ich wollte mal fragen ob man die Rails-Anwendungen "NUR" mit Nginx zum laufen bekommt oder ob es eine Lösung für Apache2-Webserver gibt da meine ganzen anwendungen mit Apache2 laufen und ich aus der Nginx Config nicht wirklich schlau werde bzw. zu faul bin um mich bei Nginx reinzulesen und meinem Kollegen der den server mitnutzt bei Nginx anzulernen.

**Comment by flowryaan** [comment]
Passenger kannst du auch für Apache2 aktivieren:
[Installing Passenger + Apache on a Linux/Unix production server](https://www.phusionpassenger.com/library/walkthroughs/deploy/ruby/ownserver/apache/oss/xenial/install_passenger.html)

Es sollte nicht viel anders sein. Du musst Passenger installieren und aktivieren und in deinem VirtualHost ein paar [Passenger spezifische Directive](https://www.phusionpassenger.com/library/walkthroughs/deploy/ruby/ownserver/apache/oss/xenial/deploy_app.html#rails_edit-apache-configuration-file) aktivieren.

Ich werde den Guide für Apache2 später ergänzen!

**Comment by flowryaan** [comment]
Apache2 Dokumentation wurde durch @levinus hinzugefügt!
