### ISSUE TITLE
rbenv: bundle: command not found

### ISSUE THREAD

**Issue by levinus** [flowryaan/mailman#4]
Ich würde sehr gerne das Webinterface installieren, habe aber noch nie etwas mit Rails gemacht und bin vermutlich deswegen auf Probleme gestoßen. Vielleicht kann mir hier ja jemand helfen.
Auf der lokalen Maschine läuft erstmal alles glatt. Wenn ich dann per `cap production deploy` deployen will bekomme ich aber (beim zweiten mal, datei ist erstellt) eine Fehlermeldung.
`**DEPLOY FAILED`
Aus dem Log kann ich auslesen, dass beim Command `rbenv exec bundle install --path /home/deploy/mailman/shared/bundle --without development test --deployment --quiet` rbenv nur mit `rbenv: bundle: command not found` geantwortet hat und deswegen der Deploy fehlgeschlagen ist.
Ich habe nun eine ganze Zeit lang probiert. bundler wurde vorher per apt-get installiert, dann hab ichs auch mit gem versucht. Durch Internet Recherche habe ich herausgefunden, dass das wohl mit der Vermischung von lokalen (user) variablen und globalen Variablen zu tun hat. Dazu auch [dieser GitHub Issue](https://github.com/rbenv/rbenv/issues/576). Ich habe ziemlich viel probiert, das Ergebnis hat sich aber nie geändert. Ich habe die Path Variablen (PATH und GEM_PATH) angepasst und mit mehr oder weniger geratetenen Pfaden gefüllt, mehrmals bundler per gem installiert und `rbenv rehash` ausgeführt.
Immer das gleiche.
Kann mir hier vielleicht noch jemand einen Tipp geben, was ich ausprobieren kann um das Problem zu lösen?

**Comment by flowryaan** [comment]
Hast du `rbenv` und `bundler` als deploy Benutzer installiert?

Wenn du dich mit dem deploy Benutzer anmeldest solltest du mit

```
ls -l ~/.rbenv/shims/
total 36
-rwxrwxr-x 1 deploy deploy 399 Dez 15 19:37 bundle
-rwxrwxr-x 1 deploy deploy 399 Dez 15 19:37 bundler
-rwxrwxr-x 1 deploy deploy 399 Dez 15 19:35 erb
-rwxrwxr-x 1 deploy deploy 399 Dez 15 19:35 gem
-rwxrwxr-x 1 deploy deploy 399 Dez 15 19:35 irb
-rwxrwxr-x 1 deploy deploy 399 Dez 15 19:35 rake
-rwxrwxr-x 1 deploy deploy 399 Dez 15 19:35 rdoc
-rwxrwxr-x 1 deploy deploy 399 Dez 15 19:35 ri
-rwxrwxr-x 1 deploy deploy 399 Dez 15 19:35 ruby
```

`bundler` als ausführbares Programm sehen. 

Alle gems die mit rbenv installiert werden sind immer nur pro Benutzer verfügbar.

**Comment by levinus** [comment]
Danke für deine Hilfe, das ganze war wohl komplett mein Fehler, ich hatte vermutlich nicht alle Commands mit dem richtigen User ausgeführt.
Nach Neuinstallation lief der deploy dann erfolgreich fertig. Webserver usw. habe ich dann noch fertig konfiguriert.
Das ganze funktioniert aber wieder nicht, vielleicht kannst du mir nochmal helfen :)
Ich bekomme nach aufrufen der konfigurierten Domain nur die Meldung von Passenger, dass etwas schiefgelaufen sei. Ein Auszug aus dem Log: 
`[ 2016-12-31 19:23:55.2045 4134/7f782c1de700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /home/deploy/mailman/current: An error occurred while starting up the preloader.
  Error ID: ef8c55b7
  Error details saved to: /tmp/passenger-error-bUMuBu.html
  Message from application: <p>It looks like Bundler could not find a gem. Maybe you didn't install all the gems that this application needs. To install your gems, please run:</p>

  <pre class="commands">bundle install</pre>

<p>If that didn't work, then the problem is probably caused by your application being run under a different environment than it's supposed to. Please check the following:</p>

<ol>
  <li>Is this app supposed to be run as the <code>deploy</code> user?</li>
  <li>Is this app being run on the correct Ruby interpreter? Below you will
      see which Ruby interpreter Phusion Passenger attempted to use.</li>
</ol>

<p>-------- The exception is as follows: -------</p>
Your bundle is locked to rake (12.0.0), but that version could not be found in any of the sources listed in your Gemfile. If you haven&#39;t changed sources, that means the author of rake (12.0.0) has removed it. You&#39;ll need to update your bundle to a different version of rake (12.0.0) that hasn&#39;t been removed in order to install. (Bundler::GemNotFound)
<pre>  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/definition.rb:179:in `rescue in specs&#39;
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/definition.rb:173:in `specs&#39;
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/definition.rb:233:in `specs_for&#39;
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/definition.rb:222:in `requested_specs&#39;
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:118:in `block in definition_method&#39;
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:19:in `setup&#39;
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler.rb:99:in `setup&#39;
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/setup.rb:20:in `&lt;top (required)&gt;&#39;
  /usr/local/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require&#39;
  /usr/local/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require&#39;
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:430:in `activate_gem&#39;
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:297:in `block in run_load_path_setup_code&#39;
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:435:in `running_bundler&#39;
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:296:in `run_load_path_setup_code&#39;
  /usr/share/passenger/helper-scripts/rack-preloader.rb:100:in `preload_app&#39;
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `&lt;module:App&gt;&#39;
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `&lt;module:PhusionPassenger&gt;&#39;
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `&lt;main&gt;&#39;</pre>`
Ich kann sehen, dass rake fehlen soll. Ist allerdings installiert.
Ich sehe außerdem, dass der Interpreter aus /usr/local benutzt wird und nicht der des Benutzers.
Ist das falsch? Wenn ja: Wie kann ich das ändern?

**Comment by levinus** [comment]
Da ich apache nutze musste ich kurz recherchieren und nach dem lösen dieses Problems auch noch einige (selbst verschuldete) Probleme lösen.
Nun bin ich aber endlich fertig diese schöne Anwendung zu installieren. Für die Apache Konfiguration habe ich mich stark an dieses Tutorial von DigitalOcean gehalten: https://www.digitalocean.com/community/tutorials/how-to-deploy-a-rails-app-with-passenger-and-apache-on-ubuntu-14-04
Eventuell werde ich mal demnächst dein Tutorial um apache erweitern und dir dazu einen Vorschlag machen.

Abschließend hab ich noch eine Frage: Wie ist das mit dem Rechtemanagement? Kann sich jeder User einloggen und alle Domains, Accounts und Aliase verwalten? Oder kann man da irgendeine Beschränkung vornehmen?

**Comment by flowryaan** [comment]
Sehr gut das du es lösen konntest! Wenn du die Dokumentation erweitern könntest wäre das super :) 

Zu deiner Frage:
Die Email Adresse die in der Environment Variable `MAILMAN_ADMIN_EMAIL` steht ist der Administrator und kann neue Domains, Accounts und Aliase hinzufügen/löschen. Alle anderen Accounts können nur Aliase hinzufügen und ihr Passwort ändern. In Zukunft möchte ich noch Domain- Admins hinzufügen. Die können dann nur für die jeweilige Domäne die Accounts verwalten.
